#!/usr/bin/env bash

echo "// This is free and unencumbered software released into the public domain.
// For more information, see LICENSE.
"
cat $@                                                                      |
sed 's://.*::'                                                              |
sed '/:/d;s/    ) {/) {/;s/^    ,/,/;s/^\([^# ]\)/@\1/'                     |
egrep '^@'                                                                  |
sed 's/^@//;s/) {//;s/}/) { }/'                                             |
tr '\n' ' '                                                                 |
sed -e 's/}/}\n/g'                                                          |
sed -e 's/;/;\n/g'                                                          |
egrep '^ .*\(.*\) { }'                                                      |
sed 's/ { }/;/;s/^ *//;s/ *[a-zA-Z0-9_]* *,/,/g;s/ *[a-zA-Z0-9_]* *)/)/g'   |
grep -v ' main('                                                            |
cat
